### ISSUE TITLE
Rust wont accept floats for version numbers in main.rs

### ISSUE THREAD

**Issue by WhiteFox08** [fparma/comfy-downtime#8]
Are we just going to be using whole numbers instead of floats when developing newer versions?

**Comment by ComfyPillow** [comment]
We Mozilla and Google chrome now.

Bigger numbers = better.

**Comment by ComfyPillow** [comment]
I'm essentially thinking of it as indicating which release it is.

Version 10 for example would indicate that this is the 10th. Release of Comfy Downtime.

IMO, Semantic versioning does not really give that many benefits in a mission like this, since "Breaking" changes are not a thing for a mission, and we do not really need things like Major, Minor and Patch Level version indicators.

The Release number is useful in itself tho, since it allows to avoid Filename conflicts with older versions of comfy Downtime, allowing you to run multiple versions next to each other.

**Comment by WhiteFox08** [comment]
Thanks.
